services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $USER
      POSTGRES_DB: possu-test
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready
      interval: 1s
      timeout: 1s
      retries: 60
